// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgvbtpwoasumjfbkmgvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFndmJ0cHdvYXN1bWpmYmttZ3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTQyNDgsImV4cCI6MjA2NTg5MDI0OH0.m8ZnL6D8XZ-3DuhEBx6_g-jFKfjpxJ5nT2MZMnVWERw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);